export const userActionTypes = {
    
    // Get current user
    GET_CURRENT_USER_REQUEST: 'GET_CURRENT_USER_REQUEST',
    GET_CURRENT_USER_SUCCESS: 'GET_CURRENT_USER_SUCCESS',
    GET_CURRENT_USER_FAILURE: 'GET_CURRENT_USER_FAILURE',

    // Register user
    REGISTER_USER_REQUEST : 'REGISTER_USER_REQUEST',
    REGISTER_USER_SUCCESS : 'REGISTER_USER_SUCCESS',
    REGISTER_USER_FAILURE : 'REGISTER_USER_FAILURE',

    // Confirm user
    CONFIRM_USER_REQUEST : 'CONFIRM_USER_REQUEST',
    CONFIRM_USER_SUCCESS : 'CONFIRM_USER_SUCCESS',
    CONFIRM_USER_FAILURE : 'CONFIRM_USER_FAILURE',
    
    // Login user
    LOGIN_USER_REQUEST : 'LOGIN_USER_REQUEST',
    LOGIN_USER_SUCCESS : 'LOGIN_USER_SUCCESS',
    LOGIN_USER_FAILURE : 'LOGIN_USER_FAILURE',
    
    // Logout user
    LOGOUT_USER_REQUEST : 'LOGOUT_USER_REQUEST',

}