export const userActionTypes = {
    // Register user
    REGISTER_USER_REQUEST : 'REGISTER_USER_REQUEST',
    REGISTER_USER_SUCCESS : 'REGISTER_USER_SUCCESS',
    REGISTER_USER_FAILURE : 'REGISTER_USER_FAILURE',
    
    // Login user
    LOGIN_USER_REQUEST : 'LOGIN_USER_REQUEST',
    LOGIN_USER_SUCCESS : 'LOGIN_USER_SUCCESS',
    LOGIN_USER_FAILURE : 'LOGIN_USER_FAILURE',
    
    // Logout user
    LOGOUT_USER_REQUEST : 'LOGOUT_USER_REQUEST',

}