/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-3",
    // "aws_cognito_identity_pool_id": "eu-west-1:088ee1f3-2437-4d09-80e8-0fa0a2aae03b",
    "aws_cognito_region": "eu-west-3",
    //"aws_user_pools_id": "eu-west-3_P1GqaZf7x",
    //"aws_user_pools_web_client_id": "7tnd2kdl7hrvelh0iksmi3ohb2",
    "aws_user_pools_id": "eu-west-3_WUzTBitZi",
    "aws_user_pools_web_client_id": "74mupa6k5o49chd7ovheu1vkcg",
    "oauth": {
        "domain": "lcdd-connection.auth.eu-west-3.amazoncognito.com"
    }
};


export default awsmobile;
